//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSEBookBank.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class History
    {
        public int BookID { get; set; }
        public string StudentName { get; set; }
        public string Title { get; set; }
        public string Auhor { get; set; }
        public int Edition { get; set; }
        public System.DateTime IssuedDate { get; set; }
        public System.DateTime DueDate { get; set; }
        public System.DateTime ReturnDate { get; set; }
    }
}
