//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSEBookBank.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MyRole
    {
        public string UserId { get; set; }
        public string RoleId { get; set; }
    }
}
