//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSEBookBank.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class student 
    {
        public string UserName { get; set; }
        public string Password { get; set; }
        public string StudentName { get; set; }
        public string RegistrationNo { get; set; }
        public Nullable<int> Fine { get; set; }
        public Nullable<int> StudentID { get; set; }
        
    }
}
